### ISSUE TITLE
parGetRank() and parGetSize() don't return int value

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/hpc-workflow-manager-full#2]
since these, ale possibly other functions too, are using the macro<->Java wrappers, that convert everything to strings, the retunr
value of these functions are strings... and need to be parseInt()'ed... I propose that the parseInt() is applied already inside the parGetRank() etc...

**Comment by velissarious** [comment]
I added the parseInt() in the parGetRank(), parGetSize() and parAddTask() in the wrapper script which all should return now integers.
This issue was caused due to the call() function of the Macro scripting language which can only return String even though the Java method returns int.
