### ISSUE TITLE
support for LSF (Ofra G.) scheduler

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/hpc-workflow-manager-full#3]
yet another scheduler that we could support

**Comment by velissarious** [comment]
I have added some support for the IBM Spectrum LSF Scheduler, I have tested it using a Virtual Machine with CentOS and the community edition of the scheduler. 

The community edition of IBM Spectrum LSF can be found here:
https://www.ibm.com/support/pages/where-do-i-download-lsf-community-edition

**Comment by xulman** [comment]
Hi,
this looks good! Could we release the updated Fiji and notify Ofra to give it a try?
Michal, do we have contact to her?
Best regards,
Vlado
